[env:morse_buddy]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
lib_deps =
    256dpi/MQTT@2.5.2
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3
    adafruit/Adafruit BusIO@^1.16.1
build_flags =
    -Isrc
    -DCORE_DEBUG_LEVEL=1
